'use strict';

// Proves keys generated by the BROWSER (Web Crypto) are compatible with our IBKR
// OAuth 1.0a signer: RSASSA-PKCS1-v1_5 signing key + RSA-OAEP encryption key,
// exported as SPKI (public) / PKCS8 (private) PEM. If this passes, a "Generate my
// keys" button in the browser can replace the OpenSSL command line entirely.

const assert = require('assert');
const crypto = require('crypto');
const http = require('http');
const { subtle } = crypto.webcrypto;
const IbkrOAuth1 = require('../lib/ibkr-oauth1');
const IbkrCpapi = require('../lib/ibkr-cpapi');
const { modPow, toBigEndianBytes } = IbkrOAuth1;

// RFC 3526 group 14 (2048-bit MODP) — a standard, public DH prime the generator
// will ship (so users never run `openssl dhparam`).
const DH_PRIME = ('FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1' +
'29024E088A67CC74020BBEA63B139B22514A08798E3404DD' +
'EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245' +
'E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED' +
'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3D' +
'C2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F' +
'83655D23DCA3AD961C62F356208552BB9ED529077096966D' +
'670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B' +
'E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9' +
'DE2BCBF6955817183995497CEA956AE515D2261898FA0510' +
'15728E5A8AACAA68FFFFFFFFFFFFFFFF').toLowerCase();
const P = BigInt('0x' + DH_PRIME);

function pem(buf, label) {
  const b64 = Buffer.from(buf).toString('base64').replace(/(.{64})/g, '$1\n');
  return `-----BEGIN ${label}-----\n${b64}\n-----END ${label}-----\n`;
}

(async () => {
  let pass = 0; const ok = (c, m) => { assert.ok(c, m); console.log('  ✓', m); pass++; };
  console.log('generate keys in-browser (Web Crypto)');
  const sigKey = await subtle.generateKey({ name: 'RSASSA-PKCS1-v1_5', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' }, true, ['sign', 'verify']);
  const encKey = await subtle.generateKey({ name: 'RSA-OAEP', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' }, true, ['encrypt', 'decrypt']);
  const sigPrivPem = pem(await subtle.exportKey('pkcs8', sigKey.privateKey), 'PRIVATE KEY');
  const encPrivPem = pem(await subtle.exportKey('pkcs8', encKey.privateKey), 'PRIVATE KEY');
  const encPubPem = pem(await subtle.exportKey('spki', encKey.publicKey), 'PUBLIC KEY');
  ok(/BEGIN PRIVATE KEY/.test(sigPrivPem) && /BEGIN PUBLIC KEY/.test(encPubPem), 'exported PKCS8/SPKI PEM');

  // The mock IBKR (server) encrypts the access-token-secret with the PUBLIC encryption
  // key, exactly as IBKR does. Our signer must decrypt it with the PRIVATE key.
  const SECRET = Buffer.from('webcrypto-generated-secret', 'utf8');
  const ATS = crypto.publicEncrypt({ key: encPubPem, padding: crypto.constants.RSA_PKCS1_PADDING }, SECRET).toString('base64');
  const CONSUMER = 'WEBCRYPTO';

  const mock = http.createServer((req, res) => { req.on('data', () => {}); req.on('end', () => {
    const send = (o, c = 200) => { res.writeHead(c, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(o)); };
    const p = req.url.split('?')[0];
    if (p === '/v1/api/oauth/live_session_token') {
      const A = BigInt('0x' + /diffie_hellman_challenge="([0-9a-f]+)"/.exec(req.headers.authorization)[1]);
      const b = BigInt('0x' + crypto.randomBytes(32).toString('hex'));
      const B = modPow(2n, b, P), K = modPow(A, b, P);
      const lst = crypto.createHmac('sha1', Buffer.from(toBigEndianBytes(K))).update(SECRET).digest('base64');
      const s = crypto.createHmac('sha1', Buffer.from(lst, 'base64')).update(CONSUMER, 'utf8').digest('hex');
      return send({ diffie_hellman_response: B.toString(16), live_session_token_signature: s, live_session_token_expiration: 600000 });
    }
    if (p === '/v1/api/iserver/auth/ssodh/init') return send({ authenticated: true, connected: true });
    if (p === '/v1/api/tickle') return send({ session: 'S', iserver: { authStatus: { authenticated: true, connected: true } } });
    if (p === '/v1/api/portfolio/accounts') return send([{ accountId: 'DU9', type: 'DEMO' }]);
    return send({ error: 'nf' }, 404);
  }); });
  await new Promise((r) => mock.listen(0, '127.0.0.1', r));

  const oauth1 = new IbkrOAuth1({ consumerKey: CONSUMER, accessToken: 'T', accessTokenSecret: ATS, signaturePem: sigPrivPem, encryptionPem: encPrivPem, dhPrime: DH_PRIME, realm: 'limited_poa' });
  const client = new IbkrCpapi({ oauth1, baseUrl: `http://127.0.0.1:${mock.address().port}/v1/api`, timeoutMs: 4000 });

  console.log('full OAuth flow with the browser-generated keys');
  const probe = await client.probe();
  ok(probe.authenticated === true, 'RSA-OAEP private key decrypts IBKR-style PKCS1 secret → LST handshake authenticates');
  const accts = await client.getAccounts();
  ok(Array.isArray(accts) && accts.length === 1, 'RSASSA-PKCS1-v1_5 key signs API requests (HMAC-SHA256 session) → getAccounts works');

  mock.close();
  console.log(`\nAll ${pass} Web Crypto key-compatibility assertions passed.`);
})().catch((e) => { console.error(e); process.exit(1); });
