// @ts-check
/**
 * sitemap-nav.spec.js — walk the site the way a user does: by clicking.
 *
 * Every navigation assertion here is a real click on a real anchor. Nothing uses
 * page.goto() to reach a page that a user would have to navigate to, because
 * goto() proves the file is served, not that anyone can find it. The one place
 * goto() appears is the sitemap HTTP audit, where "is this URL served" is
 * precisely the question.
 *
 * The spec drives itself from tests/e2e-sitemap/nav-map.json, generated by
 * `npm run navmap` from the shipped HTML. Regenerate the map after any nav
 * change; the baselines below then fail loudly if reachability regressed.
 *
 * Run headed (watchable playback):  npm run test:sitemap:headed
 * Run headless (CI):                npm run test:sitemap
 *
 * Related: docs/SITEMAP-NAV-MAP.md, issues #3107 (KC prominence), #3109 (sitemap gap).
 */
const { test, expect } = require('@playwright/test');
const navMap = require('./nav-map.json');

/**
 * Reachability baselines, locked to the measured state on 2026-07-31.
 *
 * These are a ratchet, not a target. The site is expected to *improve* against
 * them (more reachable, fewer orphans) — the assertions allow that direction and
 * fail on regression. When a fix lands, regenerate the map and tighten these.
 */
const BASELINE = {
  // Tightened after the #3109 retirement pass: 13 orphaned surfaces deleted
  // (42 pages -> 29, 24 orphans -> 11) and systems.html renamed system-health.html.
  maxOrphans: 11,
  minReachable: 18,
  maxInSitemapNotReachable: 2,
};

/** Click a link and wait for the resulting navigation to settle. */
async function clickThrough(page, selector) {
  const link = page.locator(selector).first();
  await expect(link, `expected a clickable link matching ${selector}`).toBeVisible();
  await Promise.all([page.waitForLoadState('domcontentloaded'), link.click()]);
}

const pageName = (url) => new URL(url).pathname.replace(/^\//, '') || 'index.html';

test.describe('sitemap — navigability as a user experiences it', () => {
  test('home page loads and renders its primary navigation', async ({ page }) => {
    await page.goto('/'); // entry point: the only legitimate goto for a user journey
    await expect(page).toHaveTitle(/\S/);

    const depthOne = navMap.byDepth['1'] || [];
    for (const target of depthOne) {
      await expect(
        page.locator(`a[href$="${target}"]`).first(),
        `home page should link to ${target}`,
      ).toBeAttached();
    }
  });

  test('every depth-1 page is reachable by clicking from home', async ({ page }) => {
    for (const target of navMap.byDepth['1'] || []) {
      await page.goto('/'); // reset to the start of each journey
      await clickThrough(page, `a[href$="${target}"]`);
      expect(pageName(page.url()), `clicking the ${target} nav link should land on it`).toBe(target);
      await expect(page.locator('body')).toBeVisible();
    }
  });

  test('every sitemap URL is actually served', async ({ page }) => {
    const broken = [];
    for (const entry of navMap.sitemap) {
      const target = entry === 'index.html' ? '/' : `/${entry}`;
      const response = await page.goto(target); // auditing HTTP status, not a user path
      if (!response || response.status() >= 400) {
        broken.push(`${entry} -> ${response ? response.status() : 'no response'}`);
      }
    }
    expect(broken, `sitemap advertises URLs that do not serve: ${broken.join(', ')}`).toEqual([]);
  });

  test('sitemap does not advertise pages that cannot be reached by clicking', async () => {
    const stranded = navMap.inSitemapNotReachable;
    // These are in sitemap.xml but no click path reaches them — a crawler finds
    // them, a user never can. Currently: proof, terms, welcome (#3109).
    expect(
      stranded.length,
      `pages advertised to crawlers but unreachable by clicking: ${stranded.join(', ')}`,
    ).toBeLessThanOrEqual(BASELINE.maxInSitemapNotReachable);
  });

  /**
   * #3109 retired 13 orphaned surfaces. Deleting a page that once had inbound
   * links (bookmarks, search index, old chat messages) would 404 anyone who
   * follows one, so each retired path got a server-side 302 instead — the
   * pattern routes/pages.js REDIRECTS already documents. This proves the
   * redirects exist and land somewhere real, not that the files are gone.
   */
  const RETIRED = {
    '/dream-chat.html': 'chat.html',
    '/proof.html': 'index.html',
    '/demo.html': 'stock-trader.html',
    '/kalshi-screener.html': 'kalshi-terminal.html',
    '/rag-house.html': 'faq.html',
    '/knowledgecenter.html': 'faq.html', // Knowledge Center retired 2026-09-29
    '/library.html': 'faq.html',
    '/agent-leaderboard.html': 'orchestration.html',
    '/agent-status.html': 'orchestration.html',
    '/systems.html': 'system-health.html',
    '/ibkr-connect.html': 'orchestration.html',
  };

  test('retired surfaces redirect instead of 404', async ({ page }) => {
    const broken = [];
    for (const [from, expected] of Object.entries(RETIRED)) {
      const response = await page.goto(from); // auditing redirect behaviour, not a user path
      const status = response ? response.status() : 0;
      const landed = pageName(page.url());
      if (status >= 400 || landed !== expected) {
        broken.push(`${from} -> ${landed} (${status})`);
      }
    }
    expect(broken, `retired paths must 302 to a live page: ${broken.join(', ')}`).toEqual([]);
  });

  test('orphaned-page count has not regressed', async () => {
    expect(
      navMap.orphaned.length,
      `orphaned pages grew past the baseline: ${navMap.orphaned.join(', ')}`,
    ).toBeLessThanOrEqual(BASELINE.maxOrphans);

    expect(
      navMap.reachable.length,
      'fewer pages are reachable from home than the locked baseline',
    ).toBeGreaterThanOrEqual(BASELINE.minReachable);
  });
});
