'use strict';

/**
 * track-record.js — the settlement-graded record snapshot (Verify stage).
 *
 * Turns the autopilot's exit ledger into a daily snapshot: confirmed
 * (broker-accepted) fills only, realized P&L by ET day, cumulative curve, max
 * drawdown, and the per-exit-reason table — the data layer behind the signed-in
 * journal's equity-curve/drawdown views (#3242). Product decision 2026-08-11:
 * the ledger is NOT published — this serves behind the trade gate only; the
 * public proof surface is the live demo book, not a performance record. The
 * snapshot stays book-level and hygiene-clean regardless (no balances, no share
 * quantities, no order ids — asserted by test), so a leak can't ride on it.
 *
 * HONESTY RULES (each enforced here, not promised):
 *   - confirmed fills ONLY — the `all`/decisioned view never enters this artifact;
 *   - drawdown is computed and carried at the same level as total P&L;
 *   - duplicate-collapse / no-fill exclusions are DISCLOSED as counts;
 *   - the Champion book has no settlement-graded ledger of its own yet, so it is
 *     published as `pending` — nothing shown rather than something estimated.
 *
 * Deterministic: the snapshot is a pure function of the ledger file (modulo
 * generatedAt), so it can be regenerated byte-for-byte from the same input.
 */

const fs = require('fs');
const path = require('path');
const {
  readExits, computeScorecard, preparedRows, slimStats, etParts, CONFIRMED, DEFAULT_LOG,
} = require('./trader-scorecard');

function _round(n) { return Math.round(n * 100) / 100; }

/** Pure build from a ledger path — everything below is derived, nothing invented. */
function buildTrackRecord(logPath = DEFAULT_LOG) {
  const exits = readExits(logPath);
  const confirmedRaw = exits.filter((e) => CONFIRMED.has(String(e.status || '').toLowerCase()));
  const full = computeScorecard(confirmedRaw);
  // Broker-rejected/frozen attempts carry a non-confirmed status, so the confirmed
  // filter above removes them before computeScorecard can count them — the honest
  // disclosure needs the WHOLE ledger's count of attempts that realized nothing.
  const allStats = computeScorecard(exits);
  const rows = preparedRows(confirmedRaw)
    .filter((e) => e.ts)
    .sort((a, b) => String(a.ts).localeCompare(String(b.ts)));

  // Realized P&L by ET day → cumulative curve → max drawdown on that curve.
  const byDay = new Map();
  for (const e of rows) {
    const p = etParts(e.ts);
    if (!p) continue;
    byDay.set(p.date, _round((byDay.get(p.date) || 0) + e.pnl));
  }
  const daily = [];
  let cum = 0, peak = 0, peakDate = null;
  const maxDrawdown = { amount: 0, peakDate: null, troughDate: null };
  for (const date of [...byDay.keys()].sort()) {
    cum = _round(cum + byDay.get(date));
    daily.push({ date, pnl: byDay.get(date), cum });
    if (cum > peak) { peak = cum; peakDate = date; }
    const dd = _round(peak - cum);
    if (dd > maxDrawdown.amount) {
      maxDrawdown.amount = dd; maxDrawdown.peakDate = peakDate; maxDrawdown.troughDate = date;
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    confirmedOnly: true,
    books: {
      intraday: {
        label: 'Intraday book',
        status: rows.length ? 'live' : 'no_confirmed_trades',
        stats: slimStats(full),
        byReason: full.byReason,
        daily,
        maxDrawdown,
        firstExitAt: rows.length ? rows[0].ts : null,
        lastExitAt: rows.length ? rows[rows.length - 1].ts : null,
        disclosures: {
          duplicateExitsCollapsed: full.duplicateExits,
          failedAttemptsExcluded: allStats.failedAttempts,
          estimatedTrades: full.estimatedTrades,
        },
      },
      champion: {
        label: 'Champion book',
        status: 'pending',
        note: 'The Champion allocation book does not yet write a settlement-graded ledger of its own. Its record publishes when it does — nothing is shown rather than something estimated.',
      },
    },
    method: 'Broker-accepted (confirmed) fills only, from the autopilot’s append-only exit ledger. Re-decisions of one open position are collapsed to a single round-trip; attempts the broker rejected or froze realize nothing and are excluded (both exclusions disclosed above). "Estimated" trades are positions that left the book without an autopilot fill (a protective stop filling, a manual close), valued at the last observed mark — counted, and disclosed. Days are exchange days (America/New_York).',
    disclaimers: [
      'This is the record of the house book, published for transparency. It is not investment advice and not an offer to manage money.',
      'Past performance does not predict future results. Drawdown is shown at the same prominence as profit because both are the record.',
    ],
  };
}

// ── Cached accessor + persisted artifact ─────────────────────────────────────
// Compute-on-request with a short TTL keeps the public endpoint fresh AND cheap;
// each recompute also persists the snapshot next to the ledger so the artifact
// exists on disk (idempotent — same ledger, same snapshot).
const TTL_MS = Number(process.env.TRACK_RECORD_TTL_MS || 10 * 60 * 1000);
let _cache = { at: 0, key: null, value: null };

function snapshotPathFor(logPath) {
  return path.join(path.dirname(logPath), 'track-record-snapshot.json');
}

function getTrackRecord(logPath = DEFAULT_LOG) {
  const now = Date.now();
  if (_cache.value && _cache.key === logPath && now - _cache.at < TTL_MS) return _cache.value;
  const snap = buildTrackRecord(logPath);
  _cache = { at: now, key: logPath, value: snap };
  try {
    fs.mkdirSync(path.dirname(snapshotPathFor(logPath)), { recursive: true });
    fs.writeFileSync(snapshotPathFor(logPath), JSON.stringify(snap, null, 2));
  } catch (_e) { /* persistence is best-effort; the endpoint still serves */ }
  return snap;
}

/** Test hook: drop the cache so a rewritten fixture ledger is re-read. */
function _resetCache() { _cache = { at: 0, key: null, value: null }; }

module.exports = { buildTrackRecord, getTrackRecord, snapshotPathFor, _resetCache };
