#!/usr/bin/env node
/**
 * build_doc_library.js — regenerate the Knowledge Center document library from a
 * Σ₀-grounded catalog (one Convergence Core, no sprawl).
 *
 * SOURCE OF TRUTH: data/knowledge/doc-catalog.json — a reviewed record for every
 * in-repo doc: {path, title, description, category, status, updated, grounding,
 * action, audience, mergeInto, reason}. It is the grounding for the surface: a card
 * is shown ONLY when action === "keep", and it carries a verified description +
 * status + grounding badge (NOT a scraped first line). Docs the catalog marks
 * archive/remove/merge are dropped from the Knowledge Center (and therefore from
 * the RAG grounding index, which scrapes /repo/*.md links from this page).
 *
 * Three rules decide what a visitor sees (all added in the #kc-rework pass):
 *   1. AUDIENCE. `internal` never renders — operator runbooks, deploy topology,
 *      admin surfaces. The GCE runbook names the live origin IP; it has no business
 *      on a public marketing page.
 *   2. UNCATALOGUED DOCS ARE NOT PUBLISHED. They used to render with a scraped first
 *      line and an "Unreviewed" badge, so any file landing in docs/ auto-published
 *      itself with nobody having read it. scripts/check-doc-catalog.mjs fails CI
 *      until an entry exists.
 *   3. DATED RESEARCH NOTES ROLL UP. docs/research/YYYY-MM-DD-*.md is a lab journal
 *      (87 of them); one card points at a generated docs/research/INDEX.md instead of
 *      87 cards drowning the library.
 *
 * Every card carries data-rank (this script's ordering) and data-updated (ISO date)
 * so the page can offer Recommended / Newest / A–Z without discarding the curation —
 * an unconditional client-side A→Z re-sort is what put hex-named PDFs above the FAQ.
 *
 * The ENTIRE `<div class="doc-grid">` is regenerated between the AUTO markers.
 * Idempotent. CRLF-safe (the repo's docs are mostly CRLF; the old `^---\n`
 * frontmatter strip silently failed on them, leaking `author:`/`Status:` lines as
 * summaries — fixed here by normalizing newlines on read).
 *
 * Run:  node scripts/build_doc_library.js   (then: python scripts/build_knowledge_index.py)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const KC_HTML = path.join(REPO, 'apps', 'lantern-garage', 'public', 'knowledgecenter.html');
const CATALOG = path.join(REPO, 'data', 'knowledge', 'doc-catalog.json');
const EXTERNAL_OUT = path.join(REPO, 'data', 'knowledge', 'external-sources.json');

const CORE = new Set(['README.md', 'CLAUDE.md', 'AGENTS.md', 'QUICKSTART.md']);

const MARK_START = '<!-- LIBRARY:AUTO:START (generated by scripts/build_doc_library.js — do not hand-edit) -->';
const MARK_END = '<!-- LIBRARY:AUTO:END -->';

// ── category presentation (data-cat must match the filter chips in the HTML) ──
const CATS = {
  guides:           { label: 'Guides',              icon: '📘', order: 2 },
  setup:            { label: 'Setup & integrations',icon: '🔌', order: 3 },
  trading:          { label: 'Trading',             icon: '📈', order: 4 },
  architecture:     { label: 'Architecture',        icon: '🏛️', order: 5 },
  research:         { label: 'Research',            icon: '🧪', order: 6 },
  training:         { label: 'Models & training',   icon: '🧠', order: 7 },
  creator:          { label: 'Creator suite',       icon: '🎬', order: 8 },
  reports:          { label: 'Reports',             icon: '📋', order: 9 },
};

// Categories that no longer stand alone. `ops` and `lore` are gone because their docs
// are audience:internal or off-product; the rest were one- and eight-card chips that
// only made the filter row longer (#kc-rework).
const CAT_ALIAS = {
  'convergence-io': 'architecture',
  library: 'architecture',
  ops: 'architecture',
  lore: 'guides',
};

// Essentials pinned to the front of the "All" view (independent of category).
const PIN = [
  'AGENTS.md', 'PROVIDERS.md', 'SKILLS.md', 'SECURITY.md',
  'docs/ARCHITECTURE.md', 'docs/adr/README.md', 'docs/RESEARCH-CANON.md',
  'docs/BENCHMARKS.md', 'docs/CONVERGANCE-SIGMA0-BRIEFING.md',
  'docs/MEMORY-RETRIEVAL.md', 'docs/SIGMA0-OURO-CODER.md', 'docs/SIGMA0-EV-GATE.md',
  'docs/UNISONA-1.8.md', 'docs/KEYSTONE-PRODUCT.md', 'docs/convergence-io/README.md',
];
const PIN_IDX = new Map(PIN.map((p, i) => [p, i]));

// docs/research/YYYY-MM-DD-*.md — the dated journal, rolled up rather than carded.
const DATED_NOTE = /^docs\/research\/\d{4}-\d{2}-\d{2}-/;
const NOTES_INDEX = path.join(REPO, 'docs', 'research', 'INDEX.md');

const STATUS_ORDER = { Living: 0, Reference: 1, Draft: 2, Historical: 3, Superseded: 4, Duplicate: 5, Lore: 6, Unreviewed: 7 };

// ── helpers ──────────────────────────────────────────────────────────────────
const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function readText(abs) {
  let md = fs.readFileSync(abs, 'utf8');
  if (md.charCodeAt(0) === 0xfeff) md = md.slice(1);
  return md.replace(/\r\n/g, '\n').replace(/\r/g, '\n');   // CRLF-safe
}

function stripFrontmatter(md) {
  const m = md.match(/^---\n[\s\S]*?\n---\n?/);
  return m ? md.slice(m[0].length) : md;
}

function prettyFromName(name) {
  return name.replace(/\.md$/i, '').replace(/[-_]/g, ' ').replace(/\s+/g, ' ').trim();
}

// Fallback extractor for docs NOT in the catalog (new since the audit). Skips
// metadata-ish lines so we don't surface `author:`/`Status:`/`Date:` as a summary.
const METAKEY = /^(author|owner|created|updated|date|status|version|scope|objective|deciders|approved[- ]?by|supersed|adr|project|severity|priority|commit|generated|tagline|driver|milestone|quality gate)\b\s*[:=]/i;
function fallbackMeta(md) {
  const body = stripFrontmatter(md);
  const lines = body.split('\n');
  let title = '', i = 0;
  for (; i < lines.length; i++) {
    const h = lines[i].match(/^#\s+(.*)/);
    if (h) { title = h[1].trim(); i++; break; }
    if (lines[i].trim()) break;
  }
  let summary = '';
  for (; i < lines.length; i++) {
    let ln = lines[i].trim();
    if (!ln || ln.startsWith('#') || ln.startsWith('>') || ln.startsWith('|') ||
        ln.startsWith('```') || ln.startsWith('![') || ln.startsWith('<')) continue;
    if (/^[-*_=]{2,}$/.test(ln)) continue;
    const bare = ln.replace(/^\*+|\*+$/g, '').replace(/`/g, '').trim();
    if (METAKEY.test(bare)) continue;                          // skip metadata lines
    summary = ln.replace(/[*_`>#\[\]]/g, '').replace(/\(https?:\/\/[^)]+\)/g, '').trim();
    if (summary && /[A-Za-z]/.test(summary) && !METAKEY.test(summary)) break;
    summary = '';
  }
  if (summary.length > 150) summary = summary.slice(0, 147).replace(/\s+\S*$/, '') + '…';
  return { title, summary };
}

function fmtDate(s) {
  if (!s) return '';
  const m = String(s).match(/(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return '';
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${months[+m[2] - 1]} ${m[1]}`;
}

function walkMd(dir, rel = '') {
  const out = [];
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const r = rel ? rel + '/' + e.name : e.name;
    if (e.isDirectory()) {
      if (e.name === 'archive' || e.name === 'node_modules' || e.name.startsWith('.')) continue;
      out.push(...walkMd(path.join(dir, e.name), r));
    } else if (e.isFile() && /\.md$/i.test(e.name)) out.push(r);
  }
  return out;
}

function catLabelFor(rel, cat) {
  if (rel.startsWith('docs/adr/')) return /README/i.test(rel) ? 'ADR · Index' : 'ADR';
  return (CATS[cat] && CATS[cat].label) || 'Library';
}

// Path/keyword reclassifier for the catch-all: keeps "Library" from becoming a
// dumping ground for docs the catalog leaves unbucketed (or that arrive
// uncatalogued). Only ever applied when the category would otherwise be
// 'library', so it can never override a deliberate catalog category. Rules are
// ordered most-specific first; genuinely-misc docs stay 'library' (#1708).
function reclassifyLibrary(rel) {
  const p = rel.toLowerCase();
  const rules = [
    ['setup',    /(setup|connector|oauth|deployment|tunnel|api-spec|mcp-client|ibkr|youtube|media-hosting)/],
    ['trading',  /(trader|trading|kalshi|prediction-market|portfolio)/],
    ['training', /(ouro|training|serving|\bgpu\b|weekly-training|sigma0|plt)/],
    ['creator',  /(creator|v10-|facecam|three-doors|upload)/],
    ['reports',  /(audit|-report|summary|\bqa\b|validation|feature-test)/],
    ['ops',      /(monoworkstream|rollover|repo-contract|auto-merge|work-queue|runbook|cicd|backlog|dispatch|scripts?\/)/],
  ];
  for (const [cat, re] of rules) if (re.test(p)) return cat;
  return 'library';
}

// Regenerate the dated-notes index the rollup card points at: one line per note,
// newest first, grouped by month. Generated, never hand-edited.
function writeNotesIndex(notes) {
  const byMonth = new Map();
  for (const n of notes) {
    const m = (String(n.date).match(/(\d{4})-(\d{2})/) || [])[0] || 'undated';
    if (!byMonth.has(m)) byMonth.set(m, []);
    byMonth.get(m).push(n);
  }
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const pretty = (m) => {
    const p = m.split('-');
    return p.length === 2 ? `${months[+p[1] - 1]} ${p[0]}` : 'Undated';
  };
  const out = [
    '# Research notes',
    '',
    '<!-- GENERATED by scripts/build_doc_library.js — do not hand-edit. -->',
    '',
    'Dated working notes: experiments, negative results, and design records, newest first.',
    'These are lab notebooks, not guides — a note records what was true on its date and is',
    'never revised afterwards. Findings that survive get folded into the docs above.',
    '',
    `${notes.length} notes.`,
    '',
  ];
  for (const m of [...byMonth.keys()].sort().reverse()) {
    out.push(`## ${pretty(m)}`, '');
    for (const n of byMonth.get(m)) {
      const rel = n.rel.replace(/^docs\/research\//, '');
      out.push(`- **[${n.title}](${rel})** — ${String(n.date).slice(0, 10)}`);
    }
    out.push('');
  }
  fs.writeFileSync(NOTES_INDEX, out.join('\n'), 'utf8');
}

// ── card renderer (larger panel + metadata footer: category · status · grounding · date) ──
function card(c) {
  const cat = c.cat;
  const icon = c.icon || (CATS[cat] && CATS[cat].icon) || '📄';
  const s = c.status || 'Unreviewed';
  const g = c.grounding || '';
  const attrs = [
    `class="doc-card"`, `data-cat="${cat}"`, `data-type="${c.type || 'md'}"`,
    `data-status="${s.toLowerCase()}"`, g ? `data-grounding="${g.toLowerCase()}"` : '',
    `data-audience="${c.audience || 'builder'}"`,
    // The generator's own ranking (pin → category → status → title) and an ISO date.
    // Without these the page could only re-sort by visible title text, which is how a
    // library of hex-named PDFs ended up ahead of the FAQ (#kc-rework).
    `data-rank="${String(c.rank ?? 9999).padStart(4, '0')}"`,
    c.iso ? `data-updated="${c.iso}"` : 'data-updated="0000-00-00"',
    `href="${esc(c.href)}"`, c.external ? 'target="_blank" rel="noopener"' : '',
  ].filter(Boolean).join(' ');
  const badges = [
    `<span class="doc-badge b-status" data-s="${s.toLowerCase()}">${esc(s)}</span>`,
    g ? `<span class="doc-badge b-ground" data-g="${g.toLowerCase()}">${esc(g)}</span>` : '',
  ].filter(Boolean).join('');
  const extBadge = c.external ? '<span class="doc-ext">↗ HFF</span>' : '';
  const date = c.date ? `<span class="doc-date">${esc(c.date)}</span>` : '';
  return [
    `      <a ${attrs}>`,
    `        <span class="doc-top"><span class="doc-ico">${icon}</span><span class="doc-fmt">${esc(c.fmt || 'MD')}</span></span>`,
    `        <span class="doc-title">${esc(c.title)}</span>`,
    `        <span class="doc-sum">${esc(c.summary)}</span>`,
    `        <span class="doc-foot"><span class="doc-cat">${esc(c.catLabel)}${extBadge}</span>${badges}${date}</span>`,
    `      </a>`,
  ].join('\n');
}

// ── 1. in-repo docs from the catalog ──────────────────────────────────────────
function inRepoCards() {
  let catalog = [];
  try { catalog = JSON.parse(fs.readFileSync(CATALOG, 'utf8')); } catch (e) {
    throw new Error('doc-catalog.json missing or invalid — run the audit first: ' + e.message);
  }
  const byPath = new Map(catalog.map((e) => [e.path, e]));
  const onDisk = [
    ...fs.readdirSync(REPO).filter((f) => /\.md$/i.test(f)),
    ...walkMd(path.join(REPO, 'docs'), 'docs'),
    ...walkMd(path.join(REPO, 'lore'), 'lore'),
  ];
  const seen = new Set();
  const entries = [];
  const notes = [];   // dated research notes — rolled up into one card + an index
  const stats = { keep: 0, excluded: 0, internal: 0, uncatalogued: 0, notes: 0, missing: 0 };
  for (const rel of onDisk) {
    if (seen.has(rel)) continue;
    seen.add(rel);
    // This file is OUTPUT of this script (the dated-notes index). Cataloguing it would
    // give the rollup card a second, duplicate copy of itself.
    if (rel === 'docs/research/INDEX.md') continue;
    // CORE docs are always grounded by build_knowledge_index.py; skip them here
    // UNLESS the catalog explicitly surfaces one as a card (e.g. AGENTS.md).
    if (CORE.has(rel) && !byPath.has(rel)) continue;
    const e = byPath.get(rel);
    if (e) {
      if (e.action !== 'keep') { stats.excluded++; continue; }
      // Operator-only docs never reach the public surface — infra, deploy topology,
      // admin surfaces, internal audits. This is the gate that keeps the GCE runbook
      // (which names the live origin IP) off a marketing page (#kc-rework).
      if (e.audience === 'internal') { stats.internal++; continue; }
      // Dated research notes are a journal, not a library: 99 of them on disk, and
      // every one used to claim a card. They roll up into a single card + a generated
      // index so the library stays browsable.
      if (DATED_NOTE.test(rel)) {
        notes.push({ rel, title: e.title || prettyFromName(path.basename(rel)), date: e.updated || '', summary: e.description || '' });
        stats.notes++;
        continue;
      }
      let cat = CAT_ALIAS[e.category] || (CATS[e.category] ? e.category : 'library');
      if (cat === 'library') cat = reclassifyLibrary(rel);   // rescue catch-all into a topical bucket
      entries.push({
        rel, cat, icon: e.icon,
        catLabel: catLabelFor(rel, cat),
        title: e.title || prettyFromName(path.basename(rel)),
        summary: e.description || `Reference doc · ${rel}`,
        status: e.status || 'Reference',
        grounding: e.grounding || '',
        date: fmtDate(e.updated),
        iso: (String(e.updated || '').match(/\d{4}-\d{2}-\d{2}/) || [''])[0],
        audience: e.audience || 'builder',
        pin: PIN_IDX.has(rel) ? PIN_IDX.get(rel) : 999,
      });
      stats.keep++;
    } else {
      // Uncatalogued docs are NOT published. They used to appear with a scraped
      // first line and an "Unreviewed" badge, which meant any file landing in docs/
      // auto-published itself to a public surface with nobody having read it. The
      // catalog gate (scripts/check-doc-catalog.mjs) fails CI until it has an entry.
      stats.uncatalogued++;
    }
  }
  // catalog entries whose file is gone
  for (const e of catalog) if (!seen.has(e.path) && !CORE.has(e.path)) stats.missing++;

  // sort: pinned first, then category order, then status, then title
  entries.sort((a, b) =>
    a.pin - b.pin ||
    ((CATS[a.cat] && CATS[a.cat].order) || 99) - ((CATS[b.cat] && CATS[b.cat].order) || 99) ||
    (STATUS_ORDER[a.status] ?? 9) - (STATUS_ORDER[b.status] ?? 9) ||
    a.title.localeCompare(b.title));

  const cards = entries.map((e, i) => card({
    cat: e.cat, href: '/repo/' + e.rel, icon: e.icon, title: e.title,
    summary: e.summary, catLabel: e.catLabel, status: e.status,
    grounding: e.grounding, date: e.date, iso: e.iso, audience: e.audience,
    rank: i,
  }));
  // One card for the whole dated-notes journal, ranked with the research bucket.
  if (notes.length) {
    notes.sort((a, b) => String(b.date).localeCompare(String(a.date)));
    writeNotesIndex(notes);
    cards.push(card({
      cat: 'research', href: '/repo/docs/research/INDEX.md', icon: '🗒️',
      title: `Research notes — ${notes.length} dated entries`,
      summary: `Every dated research note, newest first: experiments, negative results, and ` +
        `design records from ${notes[notes.length - 1].date?.slice(0, 7) || ''} to ${notes[0].date?.slice(0, 7) || ''}. ` +
        `Working notes, not polished guides.`,
      catLabel: 'Research', status: 'Living', grounding: 'Grounded',
      date: fmtDate(notes[0].date), iso: (String(notes[0].date).match(/\d{4}-\d{2}-\d{2}/) || [''])[0],
      audience: 'builder', rank: entries.length,
    }));
  }
  return { cards, stats };
}

// Human Flourishing Frameworks cards were removed (#kc-rework): a separate project,
// unrelated to chat, trading, or model research, taking 34 of the library's cards and
// linking off-site. data/knowledge/external-sources.json is left in place for the
// record; nothing reads it into the surface any more.

// ── main ──────────────────────────────────────────────────────────────────────
function main() {
  let html = fs.readFileSync(KC_HTML, 'utf8');
  const repo = inRepoCards();

  const block = [
    MARK_START,
    '      <!-- In-repo library (catalog-driven; scraped by build_knowledge_index.py → grounding corpus + Explore) -->',
    repo.cards.join('\n'),
    '      ' + MARK_END,
  ].join('\n');

  const reAuto = new RegExp(
    MARK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
    MARK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  if (!reAuto.test(html)) throw new Error('AUTO markers not found in knowledgecenter.html');
  html = html.replace(reAuto, block);

  fs.writeFileSync(KC_HTML, html, 'utf8');
  console.log(`doc library: ${repo.cards.length} cards (published=${repo.stats.keep}, ` +
    `notes rolled up=${repo.stats.notes}, internal withheld=${repo.stats.internal}, ` +
    `catalog-excluded=${repo.stats.excluded}, uncatalogued skipped=${repo.stats.uncatalogued})`);
  console.log('  next: python scripts/build_knowledge_index.py');
}

main();
