#!/usr/bin/env python3
"""
lightning_dispatch.py — programmatic Lightning AI Studio dispatch for Ouro training.

Auth: set LIGHTNING_USER_ID and LIGHTNING_API_KEY env vars
      (account settings → Keys → Programmatic Login)

Usage:
  python scripts/lightning_dispatch.py dispatch --steps 600 --checkpoint-uri <uri> --hf-repo ouro-checkpoints
  python scripts/lightning_dispatch.py poll --studio ouro-training
  python scripts/lightning_dispatch.py stop --studio ouro-training
"""

import argparse
import json
import os
import sys
import time


def _sdk():
    try:
        from lightning_sdk import Studio, Machine
        return Studio, Machine
    except ImportError:
        print(json.dumps({"error": "lightning_sdk_not_installed",
                          "fix": "pip install lightning-sdk"}))
        sys.exit(1)


def _check_auth():
    uid = os.environ.get("LIGHTNING_USER_ID")
    key = os.environ.get("LIGHTNING_API_KEY")
    if not uid or not key:
        print(json.dumps({
            "error": "missing_credentials",
            "required": ["LIGHTNING_USER_ID", "LIGHTNING_API_KEY"],
            "where": "lightning.ai → account settings → Keys → Programmatic Login",
        }))
        sys.exit(1)
    return uid, key


STUDIO_NAME = os.environ.get("LIGHTNING_STUDIO_NAME", "ouro-training")

TRAIN_SCRIPT = """#!/usr/bin/env python3
# Auto-generated by training-dispatcher — do not edit manually
import subprocess, sys, json
import os

HF_REPO = "{hf_repo}"
CHECKPOINT_FILE = "{checkpoint_file}"
STEPS = {steps}

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "huggingface_hub", "zstandard"], check=True)

import csf
from huggingface_hub import hf_hub_download, upload_file

if CHECKPOINT_FILE:
    local_csf = hf_hub_download(repo_id=HF_REPO, filename=CHECKPOINT_FILE, repo_type="model")
    csf.unpack(local_csf, "/tmp/checkpoint")
    resume_arg = ["--resume_from", "/tmp/checkpoint"]
else:
    resume_arg = []

result = subprocess.run(
    [sys.executable, "scripts/train_ouro.py",
     *resume_arg,
     "--max_steps", str(STEPS),
     "--seq_len", "1536",
     "--output_dir", "/tmp/output"],
    check=True
)

manifest = csf.pack(["/tmp/output"], "/tmp/output.csf")
upload_file(
    path_or_fileobj="/tmp/output.csf",
    path_in_repo="output.csf",
    repo_id=HF_REPO,
    repo_type="model",
)
print(json.dumps({{"status": "done", "steps": STEPS,
                   "sha256": manifest.get("footer_sha256")}}))
"""


def cmd_dispatch(args):
    _check_auth()
    Studio, Machine = _sdk()

    hf_repo = args.hf_repo or os.environ.get("HF_TRAINING_REPO", "ouro-checkpoints")
    checkpoint_uri = args.checkpoint_uri or ""
    checkpoint_file = os.path.basename(checkpoint_uri) if checkpoint_uri else ""
    steps = args.steps

    # Write the training script to a temp file for upload
    script_content = TRAIN_SCRIPT.format(
        hf_repo=hf_repo,
        checkpoint_file=checkpoint_file,
        steps=steps,
    )
    script_path = "/tmp/ouro_train_lightning.py"
    with open(script_path, "w") as f:
        f.write(script_content)

    studio = None
    try:
        studio = Studio(name=STUDIO_NAME)
        studio.start()
        studio.switch_machine(Machine.T4)

        # Upload the training script into the studio
        studio.upload_file(script_path, "/teamspace/studios/this_studio/ouro_train_lightning.py")

        # Run asynchronously — the studio keeps running; poll with cmd_poll
        studio.run("nohup python ouro_train_lightning.py > /tmp/train.log 2>&1 &")

        result = {
            "status": "running",
            "studio": STUDIO_NAME,
            "machine": "T4",
            "steps": steps,
            "checkpoint_uri": checkpoint_uri,
            "log_path": "/tmp/train.log",
            "poll_cmd": f"python scripts/lightning_dispatch.py poll --studio {STUDIO_NAME}",
        }
    except Exception as e:
        result = {"error": str(e), "studio": STUDIO_NAME}

    print(json.dumps(result))


def cmd_poll(args):
    _check_auth()
    Studio, Machine = _sdk()

    try:
        studio = Studio(name=args.studio)
        status = studio.status

        # Try to read the last line of the training log
        last_line = None
        try:
            raw = studio.run("tail -1 /tmp/train.log 2>/dev/null || echo ''")
            last_line = (raw or "").strip()
        except Exception:
            pass

        done = last_line and '"status": "done"' in last_line
        result = {
            "studio": args.studio,
            "studio_status": str(status),
            "status": "done" if done else "running",
            "last_log_line": last_line,
        }
    except Exception as e:
        result = {"error": str(e), "studio": args.studio}

    print(json.dumps(result))


def cmd_stop(args):
    _check_auth()
    Studio, Machine = _sdk()

    try:
        studio = Studio(name=args.studio)
        studio.stop()
        result = {"status": "stopped", "studio": args.studio}
    except Exception as e:
        result = {"error": str(e), "studio": args.studio}

    print(json.dumps(result))


def main():
    parser = argparse.ArgumentParser(description="Lightning AI dispatch for Ouro training")
    sub = parser.add_subparsers(dest="command")

    p_dispatch = sub.add_parser("dispatch")
    p_dispatch.add_argument("--steps", type=int, default=600)
    p_dispatch.add_argument("--checkpoint-uri", default="")
    p_dispatch.add_argument("--hf-repo", default="")

    p_poll = sub.add_parser("poll")
    p_poll.add_argument("--studio", default=STUDIO_NAME)

    p_stop = sub.add_parser("stop")
    p_stop.add_argument("--studio", default=STUDIO_NAME)

    args = parser.parse_args()
    if args.command == "dispatch":
        cmd_dispatch(args)
    elif args.command == "poll":
        cmd_poll(args)
    elif args.command == "stop":
        cmd_stop(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
