<#
.SYNOPSIS
    Install / refresh the stable auto-deploy (port 4177) as a repo-managed unit.

.DESCRIPTION
    The stable worktree (C:\dev\lantern-os-stable, served publicly on :4177 via the
    Cloudflare tunnel) is kept up to origin/master by a Windows scheduled task
    (KeystoneAutoDeployStable) that runs the deploy script every 5 minutes.

    Two facts shape this script:

      1. The RUNNING copy of the deploy script must live OUTSIDE any repo checkout,
         because the deploy performs `git reset --hard origin/master` on the stable
         worktree -- a copy inside a checkout could be yanked out from under itself
         mid-deploy. The tracked, authoritative source is scripts/auto-deploy-stable.ps1;
         this script COPIES it to the out-of-repo running path so the two can never
         drift by hand (the old failure mode).

      2. The task must run with NO visible console window. `powershell.exe -File ...`
         under an Interactive logon flashes a terminal every 5 minutes; launching via
         a `wscript` VBS wrapper (window style 0) never shows one. The server the
         script starts is already launched -WindowStyle Hidden.

    Idempotent: safe to re-run any time (that's how Start-DualServers keeps the
    running copy synced). Use -Unregister to remove the task + generated files.

    ASCII-only on purpose (Windows PowerShell 5.1 reads scripts as cp1252).

.PARAMETER RepoRoot
    Main checkout holding the tracked source script. Defaults to this script's repo.

.PARAMETER RunningCopy
    Out-of-repo path the task actually executes. Default C:\dev\deploy-stable-from-master.ps1.

.PARAMETER LauncherVbs
    Hidden wscript wrapper the task invokes. Default C:\dev\deploy-stable-hidden.vbs.

.PARAMETER IntervalMinutes
    How often the deploy runs. Default 5.

.PARAMETER Unregister
    Remove the scheduled task and the generated running-copy + launcher files.

.EXAMPLE
    pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/Register-AutoDeployStable.ps1
.EXAMPLE
    pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/Register-AutoDeployStable.ps1 -Unregister
#>
param(
    [string]$RepoRoot        = (Split-Path -Parent $PSScriptRoot),
    [string]$RunningCopy     = 'C:\dev\deploy-stable-from-master.ps1',
    [string]$LauncherVbs     = 'C:\dev\deploy-stable-hidden.vbs',
    [int]$IntervalMinutes    = 5,
    [switch]$Unregister
)

$ErrorActionPreference = 'Stop'
$TaskName = 'KeystoneAutoDeployStable'
$Source   = Join-Path $RepoRoot 'scripts\auto-deploy-stable.ps1'

function Ok($m)   { Write-Host "  [OK] $m"   -ForegroundColor Green }
function Warn($m) { Write-Host "  [WARN] $m" -ForegroundColor Yellow }
function Step($m) { Write-Host "  $m"        -ForegroundColor Cyan }

if ($Unregister) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Ok "Removed scheduled task '$TaskName'."
    } else {
        Warn "No scheduled task named '$TaskName'."
    }
    foreach ($f in @($RunningCopy, $LauncherVbs)) {
        if (Test-Path $f) { Remove-Item $f -Force; Ok "Deleted $f" }
    }
    exit 0
}

# --- 1. Sync the authoritative tracked script to the out-of-repo running copy ---
if (-not (Test-Path $Source)) {
    Write-Host "  [ERR] Tracked source not found: $Source" -ForegroundColor Red
    exit 1
}
$dir = Split-Path $RunningCopy -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
Copy-Item -LiteralPath $Source -Destination $RunningCopy -Force
Ok "Synced deploy script -> $RunningCopy"

# --- 2. Write the hidden wscript launcher (no console flash) ---
$vbs = @"
' Auto-generated by scripts/Register-AutoDeployStable.ps1 - DO NOT EDIT.
' Hidden launcher for the $TaskName scheduled task: runs the deploy script
' with NO console window (window style 0) so the ${IntervalMinutes}-minute deploy
' cycle stops flashing a terminal in the user session. The server the script
' starts is already launched -WindowStyle Hidden.
CreateObject("WScript.Shell").Run _
  "powershell.exe -NoProfile -ExecutionPolicy Bypass -File $RunningCopy", 0, False
"@
Set-Content -Path $LauncherVbs -Value $vbs -Encoding ASCII
Ok "Wrote hidden launcher -> $LauncherVbs"

# --- 3. Register / refresh the scheduled task ---
$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$LauncherVbs`""

# Repeat forever from "now" at the requested cadence. A ~10y duration stands in for
# "indefinite" (some Windows builds reject TimeSpan.MaxValue on -RepetitionDuration).
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

# Interactive logon as the current user: the deploy runs in the user session (same
# place the stable server lives) and inherits the desktop, but the VBS wrapper keeps
# it windowless. Overlapping runs are also guarded inside the script by a file lock.
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
$settings  = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30) `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null
Ok "Registered '$TaskName' (every $IntervalMinutes min, hidden)."

Write-Host ""
Step "Stable auto-deploy is repo-managed:"
Write-Host "    source (tracked): scripts/auto-deploy-stable.ps1" -ForegroundColor Gray
Write-Host "    running copy:     $RunningCopy" -ForegroundColor Gray
Write-Host "    hidden launcher:  $LauncherVbs" -ForegroundColor Gray
Write-Host "    log:              C:\dev\auto-deploy-stable.log" -ForegroundColor Gray
Write-Host "    remove:           scripts/Register-AutoDeployStable.ps1 -Unregister" -ForegroundColor Gray
Write-Host ""
